// web-invoices.jsx — Three invoice templates rendered at A4-scaled preview.
// Templates: Klasik, Modern, Minimal
// Props: acc (accent color), data (invoice payload)
//
// Watermark "Generated by TutorLog" is added by the outer .a4 wrapper.

// -------- Sample data --------
const sampleInvoice = {
  no: 'INV-2026/06-014',
  date: '30 Juni 2026',
  due: '7 Juli 2026',
  period: '1 – 30 Juni 2026',
  from: {
    name: 'Rina Novianti',
    lines: ['Guru Matematika & Fisika', 'Jakarta Selatan', 'rina@tutorlog.id · 0812-3456-7890'],
  },
  to: {
    name: 'Bpk. Ahmad Wijaya',
    lines: ['Orang tua Bintang Wijaya', 'Kelas 10 – SMA Al-Azhar', 'Jl. Kemang Raya No. 42, Jakarta Selatan'],
  },
  bank: { bank: 'BCA', no: '1234 5678 9012', name: 'Rina Novianti' },
  items: [
    { date: '03 Jun', desc: 'Matematika · Trigonometri', h: 1.5, rate: 120000 },
    { date: '05 Jun', desc: 'Matematika · Latihan Soal', h: 1.5, rate: 120000 },
    { date: '10 Jun', desc: 'Fisika · Gerak Lurus', h: 2.0, rate: 130000 },
    { date: '12 Jun', desc: 'Matematika · Trigonometri', h: 1.5, rate: 120000 },
    { date: '17 Jun', desc: 'Fisika · Hukum Newton', h: 2.0, rate: 130000 },
    { date: '19 Jun', desc: 'Matematika · Persiapan UH', h: 1.5, rate: 120000 },
    { date: '24 Jun', desc: 'Fisika · Energi & Usaha', h: 2.0, rate: 130000 },
    { date: '26 Jun', desc: 'Matematika · Review UH', h: 1.5, rate: 120000 },
  ],
  notes: 'Terima kasih atas kepercayaannya. Pembayaran dapat ditransfer ke rekening di bawah paling lambat 7 Juli 2026.',
};

function subtotalOf(items) { return items.reduce((s, it) => s + it.h * it.rate, 0); }
function formatIDR(n) { return 'Rp ' + n.toLocaleString('id-ID'); }
function totalHoursOf(items) { return items.reduce((s, it) => s + it.h, 0); }

// -------- KLASIK --------
function TplKlasik({ acc = '#006C53', data = sampleInvoice }) {
  const sub = subtotalOf(data.items);
  const hours = totalHoursOf(data.items);
  return (
    <div className="tpl tpl-klasik" style={{ ['--acc']: acc }}>
      <div className="k-header">
        <div>
          <div className="brand-line">
            <span className="dot"></span>
            <span className="nm">Rina Novianti · Bimbel Privat</span>
          </div>
          <h1>INVOICE</h1>
          <div className="subj">Rekap sesi les periode {data.period}</div>
        </div>
        <div className="no">
          <div className="lbl">NOMOR</div>
          <div className="val">{data.no}</div>
          <div className="lbl" style={{ marginTop: 6 }}>TANGGAL</div>
          <div className="val">{data.date}</div>
        </div>
      </div>

      <div className="k-parties">
        <div className="col">
          <div className="lbl">DARI</div>
          <div className="n">{data.from.name}</div>
          <div className="d">{data.from.lines.map((l, i) => <div key={i}>{l}</div>)}</div>
        </div>
        <div className="col">
          <div className="lbl">DITAGIH KEPADA</div>
          <div className="n">{data.to.name}</div>
          <div className="d">{data.to.lines.map((l, i) => <div key={i}>{l}</div>)}</div>
        </div>
      </div>

      <table className="k-table">
        <thead>
          <tr>
            <th style={{ width: '60px' }}>Tgl</th>
            <th>Deskripsi</th>
            <th className="right mono" style={{ width: '46px' }}>Jam</th>
            <th className="right mono" style={{ width: '80px' }}>Tarif/jam</th>
            <th className="right mono" style={{ width: '90px' }}>Subtotal</th>
          </tr>
        </thead>
        <tbody>
          {data.items.map((it, i) => (
            <tr key={i}>
              <td>{it.date}</td>
              <td>{it.desc}</td>
              <td className="right mono">{it.h.toFixed(1)}</td>
              <td className="right mono">{formatIDR(it.rate)}</td>
              <td className="right mono">{formatIDR(it.h * it.rate)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="k-total-block">
        <div className="row">
          <span>Total jam</span>
          <span className="val">{hours.toFixed(1)} jam</span>
        </div>
        <div className="row">
          <span>Subtotal</span>
          <span className="val">{formatIDR(sub)}</span>
        </div>
        <div className="row total">
          <span className="lbl">TOTAL TAGIHAN</span>
          <span className="val">{formatIDR(sub)}</span>
        </div>
      </div>

      <div className="k-notes">
        <div className="lbl">CATATAN</div>
        <div className="body">{data.notes}</div>
        <div className="k-bank">
          <div><div className="lbl">Bank</div><div className="val">{data.bank.bank}</div></div>
          <div><div className="lbl">No. Rekening</div><div className="val">{data.bank.no}</div></div>
          <div><div className="lbl">Atas Nama</div><div className="val">{data.bank.name}</div></div>
        </div>
      </div>
    </div>
  );
}

// -------- MODERN --------
function TplModern({ acc = '#006C53', data = sampleInvoice }) {
  const sub = subtotalOf(data.items);
  return (
    <div className="tpl tpl-modern" style={{ ['--acc']: acc }}>
      <div className="m-strip"></div>

      <div className="m-head">
        <div>
          <div className="sub">Rina Novianti · Bimbel Privat</div>
          <h1>Invoice.</h1>
        </div>
        <div className="meta">
          <div className="row"><span className="lbl">No.</span><span className="val">{data.no}</span></div>
          <div className="row"><span className="lbl">Tanggal</span><span className="val">{data.date}</span></div>
          <div className="row"><span className="lbl">Jatuh tempo</span><span className="val">{data.due}</span></div>
          <div className="row"><span className="lbl">Periode</span><span className="val">{data.period}</span></div>
        </div>
      </div>

      <div className="m-parties">
        <div className="col">
          <div className="lbl">Dari</div>
          <div className="n">{data.from.name}</div>
          <div className="d">{data.from.lines.map((l, i) => <div key={i}>{l}</div>)}</div>
        </div>
        <div className="col">
          <div className="lbl">Ditagihkan ke</div>
          <div className="n">{data.to.name}</div>
          <div className="d">{data.to.lines.map((l, i) => <div key={i}>{l}</div>)}</div>
        </div>
      </div>

      <table className="m-table">
        <thead>
          <tr>
            <th style={{ width: '60px' }}>Tgl</th>
            <th>Deskripsi</th>
            <th className="right mono" style={{ width: '46px' }}>Jam</th>
            <th className="right mono" style={{ width: '80px' }}>Tarif</th>
            <th className="right mono" style={{ width: '90px' }}>Subtotal</th>
          </tr>
        </thead>
        <tbody>
          {data.items.map((it, i) => (
            <tr key={i}>
              <td>{it.date}</td>
              <td>{it.desc}</td>
              <td className="right mono">{it.h.toFixed(1)}</td>
              <td className="right mono">{formatIDR(it.rate)}</td>
              <td className="right mono">{formatIDR(it.h * it.rate)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="m-total-badge">
        <span className="lbl">Total</span>
        <span className="val">{formatIDR(sub)}</span>
      </div>

      <div className="m-foot">
        <div className="box">
          <div className="lbl">Catatan</div>
          <div className="body">{data.notes}</div>
        </div>
        <div className="box bank">
          <div className="lbl">Transfer ke {data.bank.bank}</div>
          <div className="val">{data.bank.no}</div>
          <div className="body" style={{ marginTop: 2 }}>a/n {data.bank.name}</div>
        </div>
      </div>
    </div>
  );
}

// -------- MINIMAL --------
function TplMinimal({ acc = '#006C53', data = sampleInvoice }) {
  const sub = subtotalOf(data.items);
  return (
    <div className="tpl tpl-minimal" style={{ ['--acc']: acc }}>
      <h1 className="mn-title">INVOICE</h1>
      <div className="mn-underline"></div>

      <div className="mn-head">
        <div className="col">
          <div className="lbl">NOMOR</div>
          <div className="val">{data.no}</div>
          <div className="sub" style={{ marginTop: 6 }}>{data.date} · Jatuh tempo {data.due}</div>
        </div>
        <div className="col">
          <div className="lbl">DARI</div>
          <div className="val">{data.from.name}</div>
          <div className="sub">{data.from.lines[0]}<br/>{data.from.lines[2]}</div>
        </div>
        <div className="col">
          <div className="lbl">DITAGIH KE</div>
          <div className="val">{data.to.name}</div>
          <div className="sub">{data.to.lines[0]}<br/>{data.to.lines[1]}</div>
        </div>
      </div>

      <table className="mn-table">
        <thead>
          <tr>
            <th style={{ width: '55px' }}>Tgl</th>
            <th>Deskripsi sesi</th>
            <th className="right mono" style={{ width: '46px' }}>Jam</th>
            <th className="right mono" style={{ width: '90px' }}>Tarif</th>
            <th className="right mono" style={{ width: '100px' }}>Subtotal</th>
          </tr>
        </thead>
        <tbody>
          {data.items.map((it, i) => (
            <tr key={i}>
              <td>{it.date}</td>
              <td>{it.desc}</td>
              <td className="right mono">{it.h.toFixed(1)}</td>
              <td className="right mono">{formatIDR(it.rate)}</td>
              <td className="right mono">{formatIDR(it.h * it.rate)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="mn-total-row">
        <span className="lbl">TOTAL</span>
        <span className="val">{formatIDR(sub)}</span>
      </div>

      <div className="mn-foot">
        <div className="box">
          <div className="lbl">CATATAN</div>
          <div className="body">{data.notes}</div>
        </div>
        <div className="box bank">
          <div className="lbl">TRANSFER KE</div>
          <div className="val">{data.bank.bank} · {data.bank.no}</div>
          <div className="body">a/n {data.bank.name}</div>
        </div>
      </div>
    </div>
  );
}

// -------- Wrapper: A4 page with watermark --------
function A4Page({ children }) {
  return (
    <div className="a4">
      {children}
      <div className="wm-gen">Generated by TutorLog</div>
    </div>
  );
}

Object.assign(window, { TplKlasik, TplModern, TplMinimal, A4Page, sampleInvoice, subtotalOf, formatIDR, totalHoursOf });
