import type { ReactNode } from "react";

interface A4PageProps {
  children: ReactNode;
}

export default function A4Page({ children }: A4PageProps) {
  return (
    <div className="a4">
      {children}
      <div className="wm-gen">Generated by TutorLog</div>
    </div>
  );
}