import type { ReactNode, Ref } from "react";

interface A4PageProps {
  children: ReactNode;
  pageRef?: Ref<HTMLDivElement>;
  variant?: "preview" | "export" | "measure";
  pageNumber?: number;
}

export default function A4Page({ children, pageRef, variant = "preview", pageNumber }: A4PageProps) {
  const isExport = variant === "export";
  const isMeasure = variant === "measure";
  const className = isExport
    ? "a4 a4--export"
    : isMeasure
      ? "a4 a4--measure"
      : "a4";

  return (
    <div
      ref={pageRef}
      className={className}
      data-invoice-page={isMeasure ? undefined : ""}
      aria-label={pageNumber ? `Halaman invoice ${pageNumber}` : undefined}
    >
      {children}
      {isExport && <div className="wm-gen">Generated by TutorLog</div>}
    </div>
  );
}
