import type { ReactNode, Ref } from "react";

interface A4PageProps {
  children: ReactNode;
  pageRef?: Ref<HTMLDivElement>;
}

export default function A4Page({ children, pageRef }: A4PageProps) {
  return (
    <div ref={pageRef} className="a4">
      {children}
      <div className="wm-gen">Generated by TutorLog</div>
    </div>
  );
}
